# Generated by Django 3.2.7 on 2021-09-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('calificacion', models.FloatField(default=0)),
                ('marca', models.CharField(default='', max_length=20)),
                ('ref', models.CharField(default='', max_length=100)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.consola')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.categoriajuego')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('calificacion', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.videojuego')),
            ],
        ),
    ]
