# Generated by Django 3.2.7 on 2021-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='marca',
            new_name='fabricante',
        ),
        migrations.AlterField(
            model_name='categoriajuego',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
